cryptr:
  audience: http://localhost:3000 # Fill here with audience we provided you
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.cryptr.eu/t/shark-academy # change with provided value
          jwk-set-uri: http://auth.cryptr.eu/t/shark-academy/.well-known # change with provided value
